language: python
python:
  - "3.6"
  - "3.5"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: pytest
env:
  - CODECOV_TOKEN="a4163717-3c5f-4519-a231-4684075d1ba9"
